### ISSUE TITLE
defining multiple node exporter in single exporter_proxy

### ISSUE THREAD

**Issue by chitenderkumar** [rrreeeyyy/exporter_proxy#4]
Hey Hi,

is it possible to provide multiple endpoints of node_exporter of different server in config.yml for exporter_proxy service.

we have a use case where we want to leverage this.

**Comment by rrreeeyyy** [comment]
Hello, @chitenderkumar 

Yes, it is. Here is an example configuration makes possible to provide multiple endpoints for node_exporter of different servers.

```
listen: "0.0.0.0:9099"

exporters:
  node_exporter_1:
    path: "/node_exporter_1/metrics"
    url: "http://node_exporter_1.example.com:9100/metrics"
  node_exporter_2:
    path: "/node_exporter_2/metrics"
    url: "http://node_exporter_2.example.com:9100/metrics"
```

when access to `exporter_proxy/node_exporter_1/metrics`, it returns response of `node_exporter_1.example.com:9100/metrics`. And `/node_exporter_2/metrics` will behave in the same way.
